#version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
